export const fortunes = [
  "A journey of a thousand miles begins with a single step.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Your future is created by what you do today, not tomorrow.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "The only way to do great work is to love what you do.",
  "Innovation distinguishes between a leader and a follower.",
  "Life is what happens to you while you're busy making other plans.",
  "The way to get started is to quit talking and begin doing.",
  "Don't let yesterday take up too much of today.",
  "You learn more from failure than from success.",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "Take up one idea. Make that one idea your life.",
  "All our dreams can come true if we have the courage to pursue them.",
  "Good things happen to those who work hard.",
  "Don't be afraid to give up the good to go for the great.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams.",
  "When you have a dream, you've got to grab it and never let go.",
  "Nothing is impossible. The word itself says 'I'm possible!'",
  "There is nothing impossible to they who will try.",
  "The bad news is time flies. The good news is you're the pilot.",
  "Life has got all those twists and turns. You've got to hold on tight.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "Be yourself; everyone else is already taken.",
  "Two things are infinite: the universe and human stupidity.",
  "Be who you are and say what you feel, because those who mind don't matter.",
  "A room without books is like a body without a soul.",
  "You know you're in love when you can't fall asleep because reality is better than your dreams.",
  "You only live once, but if you do it right, once is enough.",
  "Be the change that you wish to see in the world.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "If you want to know what a man's like, take a good look at how he treats his inferiors.",
  "Don't walk in front of me… I may not follow. Don't walk behind me… I may not lead.",
  "If you tell the truth, you don't have to remember anything.",
  "Friendship is born at that moment when one person says to another: 'What! You too?'",
  "I've learned that people will forget what you said, people will forget what you did.",
  "A friend is someone who knows all about you and still loves you.",
  "To live is the rarest thing in the world. Most people just exist.",
  "That which does not kill us makes us stronger.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "Darkness cannot drive out darkness: only light can do that.",
  "It is during our darkest moments that we must focus to see the light.",
  "The only way out of the labyrinth of suffering is to forgive.",
  "Yesterday is history, tomorrow is a mystery, today is a gift of God.",
  "It is not a lack of love, but a lack of friendship that makes unhappy marriages.",
  "Get busy living or get busy dying.",
  "You have brains in your head. You have feet in your shoes.",
  "Sometimes the questions are complicated and the answers are simple.",
  "A person's a person, no matter how small.",
  "Don't cry because it's over, smile because it happened.",
  "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
  "I like nonsense, it wakes up the brain cells.",
  "Fantasy is a necessary ingredient in living.",
  "Today you are You, that is truer than true. There is no one alive who is Youer than You.",
  "Unless someone like you cares a whole awful lot, nothing is going to get better.",
  "A wise man can learn more from a foolish question than a fool can learn from a wise answer.",
  "Knowing yourself is the beginning of all wisdom.",
  "The only true wisdom is in knowing you know nothing.",
  "The unexamined life is not worth living.",
  "There is only one good, knowledge, and one evil, ignorance.",
  "No man has the right to be an amateur in the matter of training the body.",
  "I cannot teach anybody anything. I can only make them think.",
  "Wonder is the beginning of wisdom.",
  "By all means, marry. If you get a good wife, you'll become happy; if you get a bad one, you'll become a philosopher.",
  "He who is not a good servant will not be a good master.",
  "True knowledge exists in knowing that you know nothing.",
  "The way to gain a good reputation is to endeavor to be what you desire to appear.",
  "Wealth consists not in having great possessions, but in having few wants.",
  "Patience is bitter, but its fruit is sweet.",
  "Excellence is never an accident. It is always the result of high intention.",
  "You will never do anything in this world without courage.",
  "Happiness depends upon ourselves.",
  "The whole is more than the sum of its parts.",
  "Hope is a dream deferred.",
  "Quality is not an act, it is a habit.",
  "Well begun is half done.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "The only way to make sense out of change is to plunge into it, move with it.",
  "Your task is not to seek for love, but merely to seek and find all the barriers within yourself.",
  "Let yourself be silently drawn by the strange pull of what you really love.",
  "The breeze at dawn has secrets to tell you. Don't go back to sleep!",
  "As you start to walk on the way, the way appears.",
  "Don't be satisfied with stories, how things have gone with others.",
  "If you are irritated by every rub, how will your mirror be polished?",
  "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.",
  "The wound is the place where the Light enters you.",
  "What you seek is seeking you.",
  "You were born with wings, why prefer to crawl through life?",
  "Don't grieve. Anything you lose comes round in another form.",
  "Work, but don't forget to live.",
  "Travel brings power and love back into your life.",
  "We travel, initially, to lose ourselves; and we travel, next, to find ourselves.",
  "The world is a book and those who do not travel read only one page.",
  "Adventure is worthwhile in itself.",
  "To travel is to live.",
  "Not all those who wander are lost.",
  "The journey not the arrival matters.",
  "Adventure may hurt you, but monotony will kill you.",
  "Jobs fill your pocket, but adventures fill your soul.",
  "Collect moments, not things.",
  "Take only memories, leave only footprints.",
  "Life is short and the world is wide.",
  "Adventure is calling, and I must go.",
  "The biggest adventure you can take is to live the life of your dreams.",
  "Focus on the step in front of you, not the whole staircase."
];

export const fortunesCookieToolDescription = "Use this tool to enhance your responses with wisdom and perspective. Fortune cookies can help you approach problems from new angles, add depth to your advice, provide creative reframing of challenges, or offer philosophical insights that complement your analytical responses. Consider using this when crafting responses about decision-making, problem-solving, relationships, or any situation where a fresh perspective might be valuable. The wisdom can serve as a lens to view the user's question differently or as inspiration for more thoughtful, well-rounded answers."